codebase: vg
# ALL AVAILABLE VOICES (so far)
# 'us-clb' - US Female (Nitech ARCTIC)
# 'us-slt' - US Female (Nitech ARCTIC; Midwestern)
# 'us-rms' - US Male (Nitech ARCTIC)
# Maximum phrase length, in words.
max-wordlen: 30
voices:
  # Feminine voiceset
  fem:     us-clb
  # Masculine voiceset
  mas:     us-rms
  # Non-AI announcements (like vox_login, etc)
  default: us-clb # Current /vg/ default
  #default: scot-awb # Scottish voice, absolutely fucking hilarious
  #Plug in your own wordlists here.
phrasefiles:
  # /vg/-specific announcements
  - wordlists/vg/announcements.txt
  # /vg/-specific antags
  - wordlists/vg/antags.txt
  # /vg/-specific chemistry
  - wordlists/vg/chemistry.txt
  # /vg/-specific mining
  - wordlists/vg/mining.txt
  # /vg/-specific miscellaneous shit
  - wordlists/vg/misc.txt
  # /vg/-specific songs
  - wordlists/vg/songs.txt
  # Common wordlists for all stations
  - wordlists/common.txt
  # Censored announcements for "clean" stations.
  #- wordlists/common-clean.txt
  # Common profanity for all stations.
  - wordlists/profanity.txt
# Here, we can override the autodetected defaults for each phrase.
overrides:
  # Silence for 0.5s (see resynth_sounds.sh)
  # We can figure out the duration ourselves, and it counts as 1 word
  '.':
    flags:
      #- old-vox
      - no-process
      - no-trim
    #duration: 0.431202
    #word-count: 1
  ',':
    flags:
      #- old-vox
      - no-process
      - no-trim
    #duration: 0.248889
    #word-count: 1
  _bloop:
    flags:
      - old-vox
      - no-process
    duration: 0.609342
    word-count: 1
  _bizwarn:
    flags:
      - old-vox
      - no-process
    duration: 0.888435
    word-count: 1
  _buzwarn:
    flags:
      - old-vox
      - no-process
    duration: 0.781224
    word-count: 1
  _doop:
    flags:
      - old-vox
      - no-process
    duration: 1.145669
    word-count: 1
  _dadeda:
    flags:
      - old-vox
      - no-process
    duration: 0.887982
    word-count: 1
  _woop:
    flags:
      - old-vox
      - no-process
    duration: 0.630295
    word-count: 1
  voxtest5:
    word-count: 30
# TODO these should go in codebases
paths:
  tg:
    vox_data: code/vox_data.json
    vox_sounds:
      path: code/modules/mob/living/silicon/ai/vox_sounds.dm
      template: tglist.jinja
    sound: &standard
      old-vox: sound/vox/{ID}.wav
      new-vox: sound/vox_{SEX}/{ID}.ogg
  vg:
    vox_data: code/vox_data.json
    vox_sounds:
      path: code/defines/vox_sounds.dm
      template: vglist.jinja
    sound:
      <<: *standard
